#!/bin/bash
export CRAWLZILLA_HOME="/opt/crawlzilla"
export PACKAGES_HOME="/opt/crawlzilla/packages"
export NUTCH_PKG="apache-nutch-1.6-bin.tar.gz"
export SOLR_PKG="apache-solr-4.0.0.tgz"
export CRAWLDB="/opt/crawlzilla/crawlDB"
export NUTCH_HOME="/opt/crawlzilla/nutch"
export TOMCAT_HOME="/opt/crawlzilla/tomcat"
export SOLR_HOME="/opt/crawlzilla/solr"
export URLS="/opt/crawlzilla/nutch/urls"
