#!/bin/bash
# 1. folder: bin, conf, README  
# 2. war file(current war) -> new war folder
# 3. write version

function copyFolder(){
    echo "step: copy folder to /tmp"
}

function main(){
    echo "main function"
    copyFolder
}

main
